"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlertCircle, ArrowRight, BarChart3, Check, ChevronDown, CircleGauge, Loader2,
  Pencil, Play, Plus, Power, Save, Sparkles, WandSparkles, X
} from "lucide-react";
import { EditableNumberInput } from "@/components/ui/EditableNumberInput";
import type { FinanceOverview, FinanceTab } from "@/components/finance/FinanceWorkspace";

type Message = { tone: "success" | "error" | "info"; text: string };
type Rule = {
  id: string; name: string; priority: number; source_type: string | null;
  financial_account_id: string | null; account_name: string | null;
  conditions: RuleDraft["conditions"]; actions: RuleDraft["actions"];
  enabled: boolean; auto_apply: boolean;
};
type RuleDraft = {
  name: string; priority: number; sourceType: string | null; financialAccountId: string | null;
  conditions: { descriptionContains?: string; descriptionStartsWith?: string; regex?: string;
    direction?: "inflow" | "outflow" | "neutral"; minimumAmountCents?: number; maximumAmountCents?: number };
  actions: { nature: string; categoryId?: string | null; includeExternalCashFlow: boolean;
    includeOperatingResult: boolean; reviewRequired: boolean };
  enabled: boolean; autoApply: boolean;
};
type Comparison = { months: number; series: Array<{ competence: string; externalInflowsCents: number;
  externalOutflowsCents: number; operatingResultCents: number; transactionCount: number; pendingCount: number }>;
  categories: Array<{ name: string; amountCents: number }> };

export function PendingCenter({ overview, onNavigate, compact = false }: {
  overview: FinanceOverview; onNavigate: (tab: FinanceTab) => void; compact?: boolean;
}) {
  const health = overview.health;
  if (!health) return null;
  const color = health.readyToClose ? "emerald" : health.score >= 70 ? "cyan" : "amber";
  if (compact) return (
    <button className="group flex w-full items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-3 text-left transition hover:border-cyan-500/30 hover:bg-zinc-900" onClick={() => onNavigate("pendencies")} type="button">
      <ScoreRing score={health.score} color={color}/>
      <span className="min-w-0 flex-1"><strong className="block text-sm text-zinc-100">Fechamento {health.readyToClose ? "pronto para concluir" : `${health.score}% preparado`}</strong><span className="block truncate text-xs text-zinc-500">{health.pendencies.length ? `${health.blockingCount} bloqueio(s) e ${health.attentionCount} ponto(s) de atenção` : "Nenhuma pendência identificada"}</span></span>
      <ArrowRight className="text-zinc-600 transition group-hover:translate-x-0.5 group-hover:text-cyan-300" size={17}/>
    </button>
  );
  return <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)]">
    <section className="flex flex-col justify-between rounded-lg border border-zinc-800 bg-zinc-900/60 p-5">
      <div><div className="flex items-center gap-3"><ScoreRing score={health.score} color={color} large/><div><p className="text-xs uppercase text-zinc-500">Prontidão mensal</p><h2 className="text-lg font-semibold text-white">{health.readyToClose ? "Pronto para fechar" : "Ainda há etapas"}</h2></div></div>
      <p className="mt-4 text-sm leading-6 text-zinc-400">O indicador considera extratos obrigatórios, integridade dos saldos, revisões e classificação. Itens de atenção não bloqueiam o fechamento.</p></div>
      <div className="mt-5 grid grid-cols-2 gap-2"><SmallStat label="Bloqueios" value={health.blockingCount} danger/><SmallStat label="Atenções" value={health.attentionCount}/></div>
    </section>
    <section className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4">
      <div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold text-white">Checklist de fechamento</h2><p className="text-xs text-zinc-500">Resolva cada item diretamente na área correspondente.</p></div><CircleGauge className="text-cyan-300" size={20}/></div>
      {health.pendencies.length ? <div className="grid gap-2 sm:grid-cols-2">{health.pendencies.map((item) => <button className="group flex items-start gap-3 rounded-md border border-zinc-800 bg-zinc-950/45 p-3 text-left hover:border-zinc-700 hover:bg-zinc-950/70" key={item.key} onClick={() => onNavigate(item.action)} type="button">
        <span className={`mt-0.5 flex h-7 min-w-7 items-center justify-center rounded-md text-xs font-bold ${item.severity === "blocking" ? "bg-rose-400/10 text-rose-300" : "bg-amber-400/10 text-amber-300"}`}>{item.count}</span>
        <span className="min-w-0 flex-1"><strong className="block text-sm text-zinc-200">{item.label}</strong><span className="mt-0.5 block text-xs leading-5 text-zinc-500">{item.description}</span></span><ArrowRight className="mt-1 shrink-0 text-zinc-700 group-hover:text-cyan-300" size={15}/>
      </button>)}</div> : <div className="flex min-h-44 flex-col items-center justify-center text-center"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-400/10 text-emerald-300"><Check size={22}/></span><strong className="mt-3 text-zinc-100">Tudo conferido</strong><p className="mt-1 max-w-sm text-sm text-zinc-500">Os controles automáticos não encontraram pendências nesta competência.</p></div>}
    </section>
  </div>;
}

export function ComparisonWorkspace({ competence, onMessage }: { competence: string; onMessage: (message: Message) => void }) {
  const [months, setMonths] = useState(6); const [data, setData] = useState<Comparison | null>(null);
  const [metric, setMetric] = useState<"operatingResultCents" | "externalInflowsCents" | "externalOutflowsCents">("operatingResultCents");
  const [loading, setLoading] = useState(true); const [hovered, setHovered] = useState<number | null>(null);
  useEffect(() => { let active = true; setLoading(true); fetch(`/api/finance/comparison?competence=${competence}&months=${months}`, { cache: "no-store" })
    .then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(errorText(payload.error)); if (active) setData(payload.comparison); })
    .catch((error) => { if (active) onMessage({ tone: "error", text: error instanceof Error ? error.message : "Falha ao carregar evolução." }); })
    .finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [competence, months, onMessage]);
  const summary = useMemo(() => comparisonSummary(data?.series ?? [], metric), [data, metric]);
  return <div className="space-y-4">
    <section className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold text-white"><BarChart3 className="text-cyan-300" size={18}/> Evolução financeira</h2><p className="text-xs text-zinc-500">Compare competências sem misturar transferências internas ao caixa consolidado.</p></div>
      <div className="flex rounded-md border border-zinc-700 bg-zinc-950 p-1">{[3,6,12].map((value) => <button className={`rounded px-3 py-1.5 text-xs ${months === value ? "bg-zinc-700 text-white" : "text-zinc-500 hover:text-white"}`} key={value} onClick={() => setMonths(value)}>{value} meses</button>)}</div></div>
      <div className="mt-4 flex gap-1 overflow-x-auto">{([['operatingResultCents','Resultado'],['externalInflowsCents','Entradas'],['externalOutflowsCents','Saídas']] as const).map(([id,label]) => <button className={`shrink-0 rounded-md px-3 py-2 text-xs font-medium ${metric === id ? "bg-cyan-400/10 text-cyan-200 ring-1 ring-cyan-400/30" : "bg-zinc-950 text-zinc-500 hover:text-zinc-200"}`} key={id} onClick={() => setMetric(id)}>{label}</button>)}</div>
      {loading ? <div className="flex h-72 items-center justify-center"><Loader2 className="animate-spin text-cyan-300"/></div> : data ? <>
        <div className="mt-4 grid gap-3 sm:grid-cols-3"><SmallStat label="Competência atual" value={money(summary.current)}/><SmallStat label="Média do período" value={money(summary.average)}/><SmallStat label="Variação mensal" value={percent(summary.change)} tone={summary.change >= 0 ? "positive" : "negative"}/></div>
        <LineChart series={data.series} metric={metric} hovered={hovered} onHover={setHovered}/>
      </> : null}
    </section>
    {data ? <section className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4"><details><summary className="flex cursor-pointer list-none items-center justify-between"><span><strong className="block text-sm text-white">Categorias com maior impacto</strong><span className="text-xs text-zinc-500">Detalhamento acumulado no período selecionado</span></span><ChevronDown className="text-zinc-500" size={17}/></summary><div className="mt-5 space-y-3">{data.categories.map((category) => { const max = Math.max(1,...data.categories.map((item) => Math.abs(item.amountCents))); return <div key={category.name}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="truncate text-zinc-300">{category.name}</span><strong className={category.amountCents < 0 ? "text-rose-300" : "text-emerald-300"}>{money(category.amountCents)}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full rounded-full ${category.amountCents < 0 ? "bg-rose-400" : "bg-emerald-400"}`} style={{ width: `${Math.abs(category.amountCents) / max * 100}%` }}/></div></div>})}</div></details></section> : null}
  </div>;
}

export function RulesWorkspace({ overview, onRefresh, onMessage }: { overview: FinanceOverview; onRefresh: () => Promise<void>; onMessage: (message: Message) => void }) {
  const [rules, setRules] = useState<Rule[]>([]); const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Rule | "new" | null>(null); const [applyRule, setApplyRule] = useState<Rule | null>(null);
  const load = async () => { setLoading(true); try { const response = await fetch("/api/finance/rules", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(errorText(payload.error)); setRules(payload.rules); } catch (error) { onMessage({ tone:"error", text:error instanceof Error?error.message:"Falha ao carregar regras." }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function deactivate(rule: Rule) { const response = await fetch(`/api/finance/rules/${rule.id}`, { method:"DELETE" }); const payload=await response.json(); if(!response.ok){onMessage({tone:"error",text:errorText(payload.error)});return;} await load(); onMessage({tone:"success",text:"Regra desativada. O histórico permaneceu preservado."}); }
  async function apply() { if(!applyRule)return; const response=await fetch(`/api/finance/rules/${applyRule.id}/apply`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({competence:overview.competence})});const payload=await response.json();if(!response.ok){onMessage({tone:"error",text:errorText(payload.error)});return;}setApplyRule(null);await Promise.all([load(),onRefresh()]);onMessage({tone:"success",text:`Regra aplicada a ${payload.result.updated} lançamento(s), sem sobrescrever classificações manuais.`}); }
  return <div className="space-y-4"><section className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold text-white"><WandSparkles className="text-cyan-300" size={18}/> Regras automáticas</h2><p className="text-xs text-zinc-500">Classifique novos extratos e reaplique critérios conhecidos com segurança.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-md bg-cyan-500 px-3 py-2 text-sm font-semibold text-zinc-950 hover:bg-cyan-400" onClick={()=>setEditing("new")}><Plus size={15}/> Nova regra</button></div>
    {loading?<div className="flex h-40 items-center justify-center"><Loader2 className="animate-spin text-cyan-300"/></div>:rules.length?<div className="mt-4 divide-y divide-zinc-800">{rules.map((rule)=><details className="group py-2" key={rule.id}><summary className="flex cursor-pointer list-none items-center gap-3 rounded-md px-2 py-2 hover:bg-zinc-950/50"><span className={`h-2 w-2 rounded-full ${rule.enabled?"bg-emerald-400":"bg-zinc-700"}`}/><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-zinc-200">{rule.name}</strong><span className="block truncate text-xs text-zinc-600">Prioridade {rule.priority} · {conditionLabel(rule.conditions)} · {rule.account_name??"Todas as contas"}</span></span><span className="hidden rounded bg-zinc-800 px-2 py-1 text-[10px] text-zinc-400 sm:inline">{rule.enabled?(rule.auto_apply?"Automática":"Manual"):"Inativa"}</span><ChevronDown className="text-zinc-600 transition group-open:rotate-180" size={16}/></summary><div className="ml-5 mt-1 grid gap-3 border-l border-zinc-800 py-3 pl-4 sm:grid-cols-[1fr_auto]"><div className="grid gap-2 text-xs text-zinc-500 sm:grid-cols-2"><span>Origem: <strong className="text-zinc-300">{sourceLabel(rule.source_type)}</strong></span><span>Destino: <strong className="text-zinc-300">{natureLabel(rule.actions.nature,overview)}</strong></span><span>Categoria: <strong className="text-zinc-300">{categoryLabel(rule.actions.categoryId,overview)}</strong></span><span>Revisão: <strong className="text-zinc-300">{rule.actions.reviewRequired?"Obrigatória":"Automática"}</strong></span></div><div className="flex flex-wrap gap-2">{rule.enabled?<IconButton icon={Play} label="Aplicar nesta competência" onClick={()=>setApplyRule(rule)}/>:null}<IconButton icon={Pencil} label="Editar regra" onClick={()=>setEditing(rule)}/>{rule.enabled?<IconButton icon={Power} label="Desativar regra" onClick={()=>void deactivate(rule)}/>:null}</div></div></details>)}</div>:<div className="py-12 text-center"><Sparkles className="mx-auto text-zinc-700"/><p className="mt-3 text-sm text-zinc-400">Nenhuma regra criada.</p><p className="text-xs text-zinc-600">Crie um critério e simule o resultado antes de ativá-lo.</p></div>}</section>
    {editing?<RuleModal overview={overview} rule={editing==="new"?null:editing} onClose={()=>setEditing(null)} onDone={async(message)=>{setEditing(null);await load();onMessage({tone:"success",text:message});}}/>:null}
    {applyRule?<ConfirmModal title="Aplicar regra nesta competência?" description={`A regra “${applyRule.name}” será aplicada aos lançamentos compatíveis de ${monthLabel(overview.competence)}. Classificações feitas manualmente não serão alteradas.`} confirm="Aplicar regra" onClose={()=>setApplyRule(null)} onConfirm={()=>void apply()}/>:null}
  </div>;
}

function RuleModal({overview,rule,onClose,onDone}:{overview:FinanceOverview;rule:Rule|null;onClose:()=>void;onDone:(message:string)=>Promise<void>}) {
  const [draft,setDraft]=useState<RuleDraft>(()=>rule?{name:rule.name,priority:rule.priority,sourceType:rule.source_type,financialAccountId:rule.financial_account_id,conditions:rule.conditions,actions:rule.actions,enabled:rule.enabled,autoApply:rule.auto_apply}:emptyRule(overview));
  const [matcher,setMatcher]=useState<"descriptionContains"|"descriptionStartsWith"|"regex">(()=>rule?.conditions.regex?"regex":rule?.conditions.descriptionStartsWith?"descriptionStartsWith":"descriptionContains");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [simulation,setSimulation]=useState<{count:number;totalCents:number;samples:Array<{id:string;date:string;description:string;amountCents:number;accountName:string}>}|null>(null);
  const payload=()=>({...draft,conditions:{...draft.conditions,[matcher]:draft.conditions[matcher],descriptionContains:matcher==="descriptionContains"?draft.conditions.descriptionContains:undefined,descriptionStartsWith:matcher==="descriptionStartsWith"?draft.conditions.descriptionStartsWith:undefined,regex:matcher==="regex"?draft.conditions.regex:undefined}});
  async function request(action:"simulate"|"save"){setBusy(true);setError("");try{const response=await fetch(action==="simulate"?"/api/finance/rules/simulate":rule?`/api/finance/rules/${rule.id}`:"/api/finance/rules",{method:action==="simulate"?"POST":rule?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action==="simulate"?{...payload(),competence:overview.competence}:payload())});const result=await response.json();if(!response.ok)throw new Error(errorText(result.error));if(action==="simulate")setSimulation(result.simulation);else await onDone(rule?"Regra atualizada.":"Regra criada e pronta para os próximos extratos.");}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível processar a regra.");}finally{setBusy(false);}}
  const conditionValue=draft.conditions[matcher]??"";
  return <Modal title={rule?"Editar regra automática":"Nova regra automática"} onClose={onClose}><div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-[1fr_110px]"><Field label="Nome da regra"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ex.: Taxas do Mercado Pago"/></Field><Field label="Prioridade"><EditableNumberInput min={1} max={9999} value={draft.priority} onValueChange={value=>setDraft({...draft,priority:value})}/></Field></div>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Origem"><select value={draft.sourceType??""} onChange={e=>setDraft({...draft,sourceType:e.target.value||null})}><option value="">Todas as origens</option><option value="nubank">Nubank</option><option value="olist">Olist</option><option value="mercado_pago">Mercado Pago</option><option value="paypal">PayPal</option><option value="generic">CSV genérico</option></select></Field><Field label="Conta"><select value={draft.financialAccountId??""} onChange={e=>setDraft({...draft,financialAccountId:e.target.value||null})}><option value="">Todas as contas</option>{overview.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field></div>
    <fieldset className="rounded-md border border-zinc-800 p-3"><legend className="px-1 text-xs font-medium text-zinc-400">Quando encontrar</legend><div className="mb-3 flex gap-1 overflow-x-auto">{([['descriptionContains','Contém'],['descriptionStartsWith','Começa com'],['regex','Expressão avançada']] as const).map(([id,label])=><button className={`shrink-0 rounded px-2.5 py-1.5 text-xs ${matcher===id?"bg-cyan-400/10 text-cyan-200":"bg-zinc-950 text-zinc-500"}`} key={id} onClick={()=>{setMatcher(id);setDraft({...draft,conditions:{...draft.conditions,[id]:conditionValue}})}} type="button">{label}</button>)}</div><input className="w-full rounded-md border border-zinc-700 px-3 py-2.5 text-sm" value={conditionValue} onChange={e=>setDraft({...draft,conditions:{...draft.conditions,[matcher]:e.target.value}})} placeholder={matcher==="regex"?"Ex.: ^TARIFA.*OLIST$":"Texto presente no lançamento"}/><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Direção"><select value={draft.conditions.direction??""} onChange={e=>setDraft({...draft,conditions:{...draft.conditions,direction:(e.target.value||undefined) as RuleDraft['conditions']['direction']}})}><option value="">Qualquer</option><option value="inflow">Entrada</option><option value="outflow">Saída</option></select></Field><MoneyField label="Valor mínimo" value={draft.conditions.minimumAmountCents} onChange={value=>setDraft({...draft,conditions:{...draft.conditions,minimumAmountCents:value}})}/><MoneyField label="Valor máximo" value={draft.conditions.maximumAmountCents} onChange={value=>setDraft({...draft,conditions:{...draft.conditions,maximumAmountCents:value}})}/></div></fieldset>
    <fieldset className="rounded-md border border-zinc-800 p-3"><legend className="px-1 text-xs font-medium text-zinc-400">Então classificar como</legend><div className="grid gap-3 sm:grid-cols-2"><Field label="Natureza"><select value={draft.actions.nature} onChange={e=>setDraft({...draft,actions:{...draft.actions,nature:e.target.value}})}>{overview.natures.map(n=><option key={n.key} value={n.key}>{n.name}</option>)}</select></Field><Field label="Categoria"><select value={draft.actions.categoryId??""} onChange={e=>setDraft({...draft,actions:{...draft.actions,categoryId:e.target.value||null}})}><option value="">Sem categoria</option>{overview.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-zinc-300"><CheckField label="Fluxo de caixa" checked={draft.actions.includeExternalCashFlow} onChange={value=>setDraft({...draft,actions:{...draft.actions,includeExternalCashFlow:value}})}/><CheckField label="Resultado operacional" checked={draft.actions.includeOperatingResult} onChange={value=>setDraft({...draft,actions:{...draft.actions,includeOperatingResult:value}})}/><CheckField label="Exigir revisão" checked={draft.actions.reviewRequired} onChange={value=>setDraft({...draft,actions:{...draft.actions,reviewRequired:value}})}/><CheckField label="Aplicar automaticamente" checked={draft.autoApply} onChange={value=>setDraft({...draft,autoApply:value})}/><CheckField label="Regra ativa" checked={draft.enabled} onChange={value=>setDraft({...draft,enabled:value})}/></div></fieldset>
    {simulation?<div className="rounded-md border border-cyan-500/20 bg-cyan-500/5 p-3"><div className="flex justify-between gap-3"><span className="text-sm text-cyan-100">{simulation.count} lançamento(s) encontrado(s)</span><strong className="text-sm text-cyan-200">{money(simulation.totalCents)}</strong></div>{simulation.samples.length?<div className="mt-2 divide-y divide-cyan-500/10">{simulation.samples.map(item=><div className="flex gap-3 py-2 text-xs" key={item.id}><span className="w-20 shrink-0 text-zinc-600">{shortDate(item.date)}</span><span className="min-w-0 flex-1 truncate text-zinc-300">{item.description}</span><span className="shrink-0 text-zinc-400">{money(item.amountCents)}</span></div>)}</div>:null}</div>:null}
    {error?<p className="rounded-md border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-100">{error}</p>:null}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button className="rounded-md border border-zinc-700 px-3 py-2 text-sm text-zinc-300" onClick={()=>void request("simulate")} disabled={busy}><Play className="mr-1.5 inline" size={14}/>Simular no mês</button><button className="rounded-md bg-cyan-500 px-4 py-2 text-sm font-semibold text-zinc-950 disabled:opacity-50" onClick={()=>void request("save")} disabled={busy}>{busy?<Loader2 className="mr-1.5 inline animate-spin" size={14}/>:<Save className="mr-1.5 inline" size={14}/>}Salvar regra</button></div></div></Modal>;
}

function LineChart({series,metric,hovered,onHover}:{series:Comparison["series"];metric:keyof Comparison["series"][number];hovered:number|null;onHover:(index:number|null)=>void}) { const values=series.map(item=>Number(item[metric]));const min=Math.min(0,...values),max=Math.max(1,...values),range=max-min;const width=760,height=230,pad=28;const points=values.map((value,index)=>({x:pad+(series.length===1?0:index/(series.length-1))*(width-pad*2),y:pad+(1-(value-min)/range)*(height-pad*2)}));const path=points.map((point,index)=>`${index?"L":"M"}${point.x},${point.y}`).join(" ");return <div className="relative mt-5 overflow-x-auto"><svg aria-label="Gráfico de evolução financeira" className="h-[250px] min-w-[620px] w-full" preserveAspectRatio="none" viewBox={`0 0 ${width} ${height}`} onMouseLeave={()=>onHover(null)} role="img"><line stroke="#3f3f46" strokeDasharray="4 6" x1={pad} x2={width-pad} y1={pad} y2={pad}/><line stroke="#3f3f46" x1={pad} x2={width-pad} y1={height-pad} y2={height-pad}/>{min<0&&max>0?<line stroke="#52525b" strokeDasharray="3 4" x1={pad} x2={width-pad} y1={pad+(1-(0-min)/range)*(height-pad*2)} y2={pad+(1-(0-min)/range)*(height-pad*2)}/>:null}<path d={path} fill="none" stroke="#22d3ee" strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" vectorEffect="non-scaling-stroke"/>{points.map((point,index)=><g key={series[index].competence} onMouseEnter={()=>onHover(index)}><circle cx={point.x} cy={point.y} fill={hovered===index?"#f4f4f5":"#18181b"} r={hovered===index?6:4} stroke="#22d3ee" strokeWidth="2" vectorEffect="non-scaling-stroke"/><circle cx={point.x} cy={point.y} fill="transparent" r="18"/></g>)}</svg><div className="flex min-w-[620px] justify-between px-3 text-[10px] text-zinc-600">{series.map(item=><span key={item.competence}>{monthShort(item.competence)}</span>)}</div>{hovered!==null?<div className="pointer-events-none absolute left-1/2 top-3 -translate-x-1/2 rounded-md border border-zinc-700 bg-zinc-950/95 px-3 py-2 text-xs shadow-xl"><strong className="text-white">{monthLabel(series[hovered].competence)}</strong><p className="mt-1 text-cyan-200">{money(Number(series[hovered][metric]))}</p><p className="text-zinc-500">{series[hovered].transactionCount} lançamentos · {series[hovered].pendingCount} pendências</p></div>:null}</div> }
function ScoreRing({score,color,large=false}:{score:number;color:string;large?:boolean}){const tone=color==="emerald"?"text-emerald-300":color==="cyan"?"text-cyan-300":"text-amber-300";return <span className={`relative flex shrink-0 items-center justify-center rounded-full ${tone} ${large?"h-16 w-16":"h-11 w-11"}`} style={{background:`conic-gradient(currentColor ${score*3.6}deg,#27272a 0)`}}><span className={`absolute rounded-full bg-zinc-900 ${large?"inset-[5px]":"inset-1"}`}/><strong className={`relative ${large?"text-sm":"text-[10px]"}`}>{score}%</strong></span>}
function SmallStat({label,value,danger=false,tone}:{label:string;value:string|number;danger?:boolean;tone?:"positive"|"negative"}){return <div className="rounded-md bg-zinc-950/60 p-3"><p className="text-[11px] text-zinc-600">{label}</p><strong className={`mt-1 block text-sm ${danger||tone==="negative"?"text-rose-300":tone==="positive"?"text-emerald-300":"text-zinc-200"}`}>{value}</strong></div>}
function IconButton({icon:Icon,label,onClick}:{icon:typeof Pencil;label:string;onClick:()=>void}){return <button aria-label={label} className="flex h-8 w-8 items-center justify-center rounded-md border border-zinc-700 text-zinc-400 hover:bg-zinc-800 hover:text-white" onClick={onClick} title={label} type="button"><Icon size={14}/></button>}
function CheckField({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-center gap-2"><input checked={checked} onChange={e=>onChange(e.target.checked)} type="checkbox"/>{label}</label>}
function MoneyField({label,value,onChange}:{label:string;value?:number;onChange:(value:number|undefined)=>void}){return <div className="relative"><Field label={label}><EditableNumberInput min={0} step={0.01} value={(value??0)/100} onValueChange={next=>onChange(Math.round(next*100))} placeholder="R$ 0,00"/></Field>{value!==undefined?<button aria-label={`Remover ${label.toLowerCase()}`} className="absolute bottom-2.5 right-2 text-zinc-600 hover:text-zinc-200" onClick={()=>onChange(undefined)} title="Remover limite" type="button"><X size={14}/></button>:null}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-xs font-medium text-zinc-400">{label}<span className="[&>input]:w-full [&>input]:rounded-md [&>input]:border [&>input]:border-zinc-700 [&>input]:px-3 [&>input]:py-2.5 [&>select]:w-full [&>select]:rounded-md [&>select]:border [&>select]:border-zinc-700 [&>select]:bg-zinc-950 [&>select]:px-3 [&>select]:py-2.5">{children}</span></label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-3" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-lg border border-zinc-700 bg-zinc-900 shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-zinc-800 bg-zinc-900 px-4 py-3"><h2 className="font-semibold text-white">{title}</h2><button aria-label="Fechar" onClick={onClose}><X size={18}/></button></header><div className="p-4">{children}</div></div></div>}
function ConfirmModal({title,description,confirm,onClose,onConfirm}:{title:string;description:string;confirm:string;onClose:()=>void;onConfirm:()=>void}){return <Modal title={title} onClose={onClose}><AlertCircle className="text-amber-300"/><p className="mt-3 text-sm leading-6 text-zinc-400">{description}</p><div className="mt-5 flex justify-end gap-2"><button className="rounded-md border border-zinc-700 px-3 py-2 text-sm" onClick={onClose}>Cancelar</button><button className="rounded-md bg-cyan-500 px-3 py-2 text-sm font-semibold text-zinc-950" onClick={onConfirm}>{confirm}</button></div></Modal>}
function emptyRule(overview:FinanceOverview):RuleDraft{return{name:"",priority:100,sourceType:null,financialAccountId:null,conditions:{descriptionContains:""},actions:{nature:overview.natures.find(n=>n.key==="operating_expense")?.key??overview.natures[0]?.key??"unclassified",categoryId:null,includeExternalCashFlow:true,includeOperatingResult:true,reviewRequired:false},enabled:true,autoApply:true}}
function comparisonSummary(series:Comparison["series"],metric:keyof Comparison["series"][number]){const values=series.map(item=>Number(item[metric]));const current=values.at(-1)??0,previous=values.at(-2)??0;return{current,average:values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0,change:previous===0?(current===0?0:100):(current-previous)/Math.abs(previous)*100}}
function conditionLabel(conditions:Rule["conditions"]){if(conditions.descriptionContains)return `Contém “${conditions.descriptionContains}”`;if(conditions.descriptionStartsWith)return `Começa com “${conditions.descriptionStartsWith}”`;if(conditions.regex)return "Expressão avançada";return "Critério combinado"}
function sourceLabel(value:string|null){return value?({nubank:"Nubank",olist:"Olist",mercado_pago:"Mercado Pago",paypal:"PayPal",generic:"CSV genérico"} as Record<string,string>)[value]??value:"Todas"}
function natureLabel(key:string,overview:FinanceOverview){return overview.natures.find(n=>n.key===key)?.name??key}function categoryLabel(id:string|null|undefined,overview:FinanceOverview){return overview.categories.find(c=>c.id===id)?.name??"Sem categoria"}
function money(cents:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100)}function percent(value:number){return new Intl.NumberFormat("pt-BR",{style:"percent",maximumFractionDigits:1}).format(value/100)}
function monthLabel(value:string){const [year,month]=value.split("-").map(Number);return new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(year,month-1,1))}function monthShort(value:string){const [year,month]=value.split("-").map(Number);return new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(new Date(year,month-1,1)).replace(".","")}
function shortDate(value:string){return new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`))}function errorText(error:unknown){if(typeof error==="string")return error;if(error&&typeof error==="object"){const candidate=error as {formErrors?:unknown;fieldErrors?:Record<string,unknown>;message?:unknown};const messages=[...(Array.isArray(candidate.formErrors)?candidate.formErrors:[]),...Object.values(candidate.fieldErrors??{}).flatMap(value=>Array.isArray(value)?value:[])].filter(value=>typeof value==="string");if(messages.length)return messages.join(" ");if(typeof candidate.message==="string")return candidate.message;}return"Revise os campos informados."}
